In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from pandas import Series,DataFrame

In [4]:
obj = pd.Series([4,7,-5,3])

In [5]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2=pd.Series([4,7,-5,3],index=['d','b','a','c'])

In [9]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2['a']

-5

In [12]:
obj2['d']=6

In [13]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [14]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [15]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [16]:
import numpy as np

In [17]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [18]:
'b' in obj2

True

In [19]:
'e' in obj2

False

In [20]:
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}

In [21]:
obj3=pd.Series(sdata)

In [22]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [23]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [24]:
states=['California','Ohio','Oregon','Texas']

In [25]:
obj4=pd.Series(sdata,index=states)

In [26]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [27]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [29]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [31]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [32]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [33]:
obj4.name='population'

In [34]:
obj4.index.name='state'

In [35]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [36]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [37]:
obj.index=['Bob','Steve','Jeff','Ryan']

In [38]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [39]:
data={'state':['Ohio','Ohio','Ohio','Neveda','Neveda','Neveda'],
      'year':[2000,2001,2002,2001,2002,2003],
      'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame=pd.DataFrame(data)

In [40]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Neveda  2001  2.4
4  Neveda  2002  2.9
5  Neveda  2003  3.2

In [41]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Neveda  2001  2.4
4  Neveda  2002  2.9

In [42]:
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Neveda  2001  2.4
4  Neveda  2002  2.9
5  Neveda  2003  3.2

In [43]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Neveda  2.4
4  2002  Neveda  2.9
5  2003  Neveda  3.2

In [44]:
frame2=pd.DataFrame(data,columns=['year','state','pop','debt'])

In [45]:
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Neveda  2.4  NaN
4  2002  Neveda  2.9  NaN
5  2003  Neveda  3.2  NaN

In [46]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [47]:
frame2['state']

0      Ohio
1      Ohio
2      Ohio
3    Neveda
4    Neveda
5    Neveda
Name: state, dtype: object

In [48]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [49]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [50]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [51]:
frame2['debt']=16.5

In [52]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Neveda  2.4  16.5
4  2002  Neveda  2.9  16.5
5  2003  Neveda  3.2  16.5

In [53]:
frame2['debt']=np.arange(6.)

In [54]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Neveda  2.4   3.0
4  2002  Neveda  2.9   4.0
5  2003  Neveda  3.2   5.0

In [55]:
val=pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [56]:
frame2['debt']=val

In [57]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Neveda  2.4   NaN
4  2002  Neveda  2.9   NaN
5  2003  Neveda  3.2   NaN

In [58]:
frame2['eastern']=frame2['state']=='Ohio'

In [59]:
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Neveda  2.4   NaN    False
4  2002  Neveda  2.9   NaN    False
5  2003  Neveda  3.2   NaN    False

In [60]:
del frame2['eastern']

In [61]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [62]:
populations={'Ohio':{2000:1.5,2001:1.7,2002:3.6},
             'Neveda':{2001:2.4,2002:2.9}}

In [63]:
frame3=pd.DataFrame(populations)

In [64]:
frame3

Ohio  Neveda
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [65]:
frame3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Neveda   NaN   2.4   2.9

In [66]:
pd.DataFrame(populations,index=[2001,2002,2003])

Ohio  Neveda
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [67]:
pdata={'Ohio':frame3['Ohio'][:-1],
       'Neveda':frame3['Neveda'][:2]}

In [68]:
pd.DataFrame(pdata)

Ohio  Neveda
2000   1.5     NaN
2001   1.7     2.4

In [69]:
frame3.index.name='year'

In [70]:
frame3.columns.name='state'

In [71]:
frame3

state  Ohio  Neveda
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [72]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [73]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Neveda', 2.4, nan],
       [2002, 'Neveda', 2.9, nan],
       [2003, 'Neveda', 3.2, nan]], dtype=object)

In [74]:
obj=pd.Series(np.arange(3),index=['a','b','c'])

In [75]:
index=obj.index

In [76]:
index

Index(['a', 'b', 'c'], dtype='object')

In [77]:
index[1:]

Index(['b', 'c'], dtype='object')

In [78]:
labels=pd.Index(np.arange(3))

In [79]:
labels

Index([0, 1, 2], dtype='int32')

In [80]:
obj2=pd.Series([1.5,-2.5,0],index=labels)

In [81]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [82]:
obj2.index is labels

True

In [83]:
frame3

state  Ohio  Neveda
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [84]:
frame3.columns

Index(['Ohio', 'Neveda'], dtype='object', name='state')

In [85]:
'Ohio' in frame3.columns

True

In [86]:
2003 in frame3.index

False

In [87]:
pd.Index(['foo','foo','bar','bar'])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [88]:
obj=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])

In [89]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [90]:
obj2=obj.reindex(['a','b','c','d','e'])

In [91]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [92]:
obj3=pd.Series(['blue','purple','yellow'],index=[0,2,4])

In [93]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [94]:
obj3.reindex(np.arange(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [95]:
frame=pd.DataFrame(np.arange(9).reshape((3,3)),index=list('acd'),columns=['Ohio','Texas','California'])

In [96]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [97]:
frame2=frame.reindex(index=list('abcd'))

In [98]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [99]:
states=['Texas','Utah','California']

In [100]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [101]:
frame.reindex(states,axis=1)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [102]:
frame.loc[list('adc'),['California','Texas']]

California  Texas
a           2      1
d           8      7
c           5      4

In [103]:
obj=pd.Series(np.arange(5.),index=list('abcde'))

In [104]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [105]:
new_obj=obj.drop('c')

In [106]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [107]:
obj.drop(list('bc'))

a    0.0
d    3.0
e    4.0
dtype: float64

In [108]:
data=pd.DataFrame(np.arange(16.).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])

In [109]:
data

one   two  three  four
Ohio       0.0   1.0    2.0   3.0
Colorado   4.0   5.0    6.0   7.0
Utah       8.0   9.0   10.0  11.0
New York  12.0  13.0   14.0  15.0

In [110]:
data.drop(index=['Colorado','Ohio'])

one   two  three  four
Utah       8.0   9.0   10.0  11.0
New York  12.0  13.0   14.0  15.0

In [111]:
data.drop(columns=['two'])

one  three  four
Ohio       0.0    2.0   3.0
Colorado   4.0    6.0   7.0
Utah       8.0   10.0  11.0
New York  12.0   14.0  15.0

In [112]:
data.drop('two',axis=1)

one  three  four
Ohio       0.0    2.0   3.0
Colorado   4.0    6.0   7.0
Utah       8.0   10.0  11.0
New York  12.0   14.0  15.0

In [113]:
data.drop(['two','four'],axis='columns')

one  three
Ohio       0.0    2.0
Colorado   4.0    6.0
Utah       8.0   10.0
New York  12.0   14.0

In [114]:
obj=pd.Series(np.arange(4.),index=list('abcd'))

In [115]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [116]:
obj['b']

1.0

In [117]:
#落伍过时的垃圾写法
obj[1]

C:\Users\DELL\AppData\Local\Temp\ipykernel_2956\1894379408.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]


1.0

In [118]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [119]:
obj[list('bad')]

b    1.0
a    0.0
d    3.0
dtype: float64

In [120]:
obj[[1,3]]

C:\Users\DELL\AppData\Local\Temp\ipykernel_2956\1781339481.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1,3]]


b    1.0
d    3.0
dtype: float64

In [121]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [122]:
obj.loc[list('bad')]

b    1.0
a    0.0
d    3.0
dtype: float64

In [123]:
obj1=pd.Series([1,2,3],index=[2,0,1])

In [124]:
obj1

2    1
0    2
1    3
dtype: int64

In [125]:
obj2=pd.Series([1,2,3],index=list('abc'))

In [126]:
obj2

a    1
b    2
c    3
dtype: int64

In [127]:
obj1[[0,1,2]]

0    2
1    3
2    1
dtype: int64

In [128]:
obj2[[0,1,2]]

C:\Users\DELL\AppData\Local\Temp\ipykernel_2956\2179584337.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj2[[0,1,2]]


a    1
b    2
c    3
dtype: int64

In [129]:
obj2.loc['b':'c']

b    2
c    3
dtype: int64

In [130]:
obj2.loc['b':'c']=5

In [131]:
obj2

a    1
b    5
c    5
dtype: int64

In [132]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
                  index=['Ohio','Colorado','Utah','New York'],
                  columns=['one','two','three','four'])

In [133]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [134]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [135]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [136]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [137]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [138]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [139]:
data[data<5]=0

In [140]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [141]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [142]:
data.loc['Colorado']

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int32

In [143]:
data.loc[['Colorado','New York']]

one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [144]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [145]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [146]:
data.iloc[[2,1]]

one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [147]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [148]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [149]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [150]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [151]:
data.loc[data.three>5]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [152]:
data.loc[data.three>=2]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [153]:
ser=pd.Series(np.arange(3.))

In [154]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [155]:
ser[-1]

KeyError: -1

In [156]:
ser2=pd.Series(np.arange(3.),index=['a','b','c'])

In [157]:
ser2[-1]

C:\Users\DELL\AppData\Local\Temp\ipykernel_2956\811950851.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[-1]


2.0

In [158]:
ser.iloc[-1]

2.0

In [159]:
ser[:2]

0    0.0
1    1.0
dtype: float64

In [160]:
data.loc[:,'one']=1

In [161]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [162]:
data.iloc[2]=5

In [163]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [164]:
data.loc[data['four']>5]=3

In [165]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [166]:
data.loc[data.three==5]['three']=6

C:\Users\DELL\AppData\Local\Temp\ipykernel_2956\1968452370.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data.three==5]['three']=6


In [167]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [168]:
data.loc[data.three==5,'three']=6

In [169]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3

In [170]:
s1=pd.Series([7.3,-2.5,3.4,1.5],index=list('acde'))

In [171]:
s2=pd.Series([-2.1,3.6,-1.5,4.,3.1],index=list('acefg'))

In [172]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [173]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [174]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [175]:
df1=pd.DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),index=['Ohio','Texas','Colorado'])

In [176]:
df2=pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [177]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [178]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [179]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [180]:
df1=pd.DataFrame({'A':[1,2]})

In [181]:
df2=pd.DataFrame({'A':[3,4]})

In [182]:
df1

A
0  1
1  2

In [183]:
df2

A
0  3
1  4

In [184]:
df1+df2

A
0  4
1  6

In [185]:
df1=pd.DataFrame(np.arange(12.).reshape((3,4)),columns=list('abcd'))

In [186]:
df2=pd.DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))

In [187]:
df2.loc[1,'b']=np.nan

In [188]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [189]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [190]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [191]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [192]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [193]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [194]:
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [195]:
arr=np.arange(12.).reshape((3,4))

In [196]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [197]:
arr[0]

array([0., 1., 2., 3.])

In [198]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [199]:
frame=pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [200]:
series=frame.iloc[0]

In [201]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [202]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [203]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [204]:
series2=pd.Series(np.arange(3),index=list('bef'))

In [205]:
series2

b    0
e    1
f    2
dtype: int32

In [206]:
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [207]:
series3=frame['d']

In [208]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [209]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [210]:
frame.sub(series,axis='index')

b   d   e
Ohio   NaN NaN NaN
Oregon NaN NaN NaN
Texas  NaN NaN NaN
Utah   NaN NaN NaN
b      NaN NaN NaN
d      NaN NaN NaN
e      NaN NaN NaN

In [211]:
frame=pd.DataFrame(np.random.standard_normal((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [212]:
frame

b         d         e
Utah    1.248313  0.783640  0.991729
Ohio    0.983824 -0.443702  0.968928
Texas   0.307625  1.599092 -0.247425
Oregon  0.844904  0.497137  0.156455

In [213]:
np.abs(frame)

b         d         e
Utah    1.248313  0.783640  0.991729
Ohio    0.983824  0.443702  0.968928
Texas   0.307625  1.599092  0.247425
Oregon  0.844904  0.497137  0.156455

In [214]:
def f1(x):
    return x.max()-x.min()

In [215]:
frame.apply(f1)

b    0.940688
d    2.042794
e    1.239154
dtype: float64

In [216]:
frame.apply(f1,axis='columns')

Utah      0.464673
Ohio      1.427526
Texas     1.846517
Oregon    0.688449
dtype: float64

In [217]:
def f2(x):
    return pd.Series([x.max(),x.min()],index=['max','min'])

In [218]:
frame.apply(f2)

b         d         e
max  1.248313  1.599092  0.991729
min  0.307625 -0.443702 -0.247425

In [219]:
def my_format(x):
    return f'{x:.2f}'

In [220]:
frame.applymap(my_format)

C:\Users\DELL\AppData\Local\Temp\ipykernel_2956\1462544007.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(my_format)


b      d      e
Utah    1.25   0.78   0.99
Ohio    0.98  -0.44   0.97
Texas   0.31   1.60  -0.25
Oregon  0.84   0.50   0.16

In [221]:
frame['e'].map(my_format)

Utah       0.99
Ohio       0.97
Texas     -0.25
Oregon     0.16
Name: e, dtype: object

In [222]:
obj=pd.Series(np.arange(4),index=list('dabc'))

In [223]:
obj

d    0
a    1
b    2
c    3
dtype: int32

In [224]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int32

In [225]:
frame=pd.DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=list('dabc'))

In [226]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [227]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [228]:
frame.sort_index(axis='columns')

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [229]:
frame.sort_index(axis='columns',ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [230]:
obj=pd.Series([4,7,-3,2])

In [231]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [232]:
obj=pd.Series([4,np.nan,7,np.nan,-3,2])

In [233]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [234]:
obj.sort_values(na_position='first')

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [235]:
frame=pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [236]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [237]:
frame.sort_values('b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [238]:
frame.sort_values(['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [239]:
obj=pd.Series([7,-5,7,4,2,0,4])

In [240]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [241]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [242]:
obj.rank(ascending=False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [243]:
frame=pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})

In [244]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [245]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [246]:
obj=pd.Series(np.arange(5),index=list('aabbc'))

In [247]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int32

In [248]:
obj.index.is_unique

False

In [249]:
obj['a']

a    0
a    1
dtype: int32

In [250]:
obj['c']

4

In [251]:
df=pd.DataFrame(np.random.standard_normal((5,3)),index=list('aabbc'))

In [252]:
df

0         1         2
a -0.464591 -1.210467  0.609956
a -0.028690 -1.032410 -0.328632
b  0.146012  0.265937  0.675507
b  1.398480  0.703537  1.386724
c  0.423927  1.098397 -0.907568

In [253]:
df.loc['b']

0         1         2
b  0.146012  0.265937  0.675507
b  1.398480  0.703537  1.386724

In [254]:
df.loc['c']

0    0.423927
1    1.098397
2   -0.907568
Name: c, dtype: float64

In [255]:
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=list('abcd'),columns=['one','two'] )                                                                                               

In [256]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [257]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [258]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [259]:
df.sum(axis='index',skipna=False)

one   NaN
two   NaN
dtype: float64

In [260]:
df.sum(axis='columns',skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [261]:
df.mean(axis='columns')

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [262]:
df.idxmax()

one    b
two    d
dtype: object

In [263]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [264]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [265]:
obj=pd.Series(['a','a','b','c']*4)

In [266]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [267]:
import pandas_datareader.data as web

In [268]:
import yfinance as yf

tickers = ['AAPL', 'IBM', 'MSFT', 'GOOG']
all_data = {ticker: yf.download(ticker) for ticker in tickers}


[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


In [269]:
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [270]:
returns = price.pct_change()

In [271]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2024-09-10 -0.003621  0.008795  0.020901  0.003143
2024-09-11  0.011585  0.022258  0.021342  0.014266
2024-09-12  0.000494  0.008195  0.009361  0.022281
2024-09-13 -0.001212  0.015028  0.008407  0.018195
2024-09-16 -0.027775  0.011034  0.001742  0.003915

In [272]:
returns['MSFT'].corr(returns['IBM'])

0.44041440423415884

In [273]:
returns['MSFT'].cov(returns['IBM'])

0.00015824352609336158

In [274]:
returns['MSFT'].corr(returns['IBM'])

0.44041440423415884

In [275]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.366708  0.430454  0.515403
IBM   0.366708  1.000000  0.440414  0.387251
MSFT  0.430454  0.440414  1.000000  0.563469
GOOG  0.515403  0.387251  0.563469  1.000000

In [276]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000776  0.000170  0.000245  0.000204
IBM   0.000170  0.000250  0.000158  0.000107
MSFT  0.000245  0.000158  0.000444  0.000185
GOOG  0.000204  0.000107  0.000185  0.000373

In [277]:
returns.corrwith(returns['IBM'])

AAPL    0.366708
IBM     1.000000
MSFT    0.440414
GOOG    0.387251
dtype: float64

In [278]:
returns.corrwith(volume)

AAPL    0.000692
IBM    -0.010167
MSFT   -0.005737
GOOG    0.036347
dtype: float64

In [279]:
obj=pd.Series(['c','a','d','a','a','b','b','c','c'])

In [280]:
uniques=obj.unique()

In [281]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [282]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [283]:
pd.value_counts(obj.to_numpy(),sort=False)

C:\Users\DELL\AppData\Local\Temp\ipykernel_2956\2733622681.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.to_numpy(),sort=False)


c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [284]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [285]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [286]:
mask=obj.isin(['b','c'])

In [287]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [288]:
to_match=pd.Series(['c','a','b','b','c','a'])

In [289]:
unique_vals=pd.Series(['c','b','a'])

In [290]:
indices=pd.Index(unique_vals).get_indexer(to_match)

In [291]:
indices

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [292]:
data=pd.DataFrame({'QU1':[1,3,4,3,4],
                   'QU2':[2,3,1,2,3],
                   'QU3':[1,5,2,4,4]})

In [293]:
data

QU1  QU2  QU3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [294]:
data['QU1'].value_counts().sort_index()

QU1
1    1
3    2
4    2
Name: count, dtype: int64

In [295]:
result = data.apply(lambda x: x.value_counts()).fillna(0)

In [296]:
result

QU1  QU2  QU3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [297]:
data=pd.DataFrame({'a':[1,1,1,2,2],
                   'b':[0,0,1,0,0]})

In [298]:
data

a  b
0  1  0
1  1  0
2  1  1
3  2  0
4  2  0

In [299]:
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
Name: count, dtype: int64